# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/train-the-trainer-student-track-OS
website:
  title: "Educational resources for teaching open research to novices"
  page-footer:
    border: false
    center: © 2026 Sarah von Grebmer zu Wolfsthurn, Sara Middleton, Malika Ihle, Felix Schönbrodt. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/train-the-trainer-student-track-OS

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
      - href: help.qmd
        text: Help
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/train-the-trainer-student-track-OS
          - text: Report a Bug
            href: https://github.com/lmu-osc/train-the-trainer-student-track-OS/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Module 1: Open Research Principles"
        contents:
          - href: materials/os-m1/os-m1-s1-reproducibility-replicability/os-m1-s1-replicability.qmd
          - href: materials/os-m1/os-m1-s2-credibility/os-m1-s2-credibility.qmd
      - section: "Module 3: Open Research Software Tools"
        contents:
          - href: materials/os-m3/os-m3-s2-r-part-i/os-m3-s2-r-part-i.qmd
          - href: materials/os-m3/os-m3-s4-git/os-m3-s4-git.qmd
          - href: materials/os-m3/os-m3-s5-github/os-m3-s5-github.qmd
          - href: materials/os-m3/os-m3-s6-quarto/os-m3-s6-quarto.qmd
          - href: materials/os-m3/os-m3-s1-zotero/os-m3-s1-zotero.qmd
          - href: materials/os-m3/os-m3-s8-simulations/os-m3-s8-simulations.qmd
# End Website

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
    include-in-header:
      - file: matomo-analytics.html
    include-after-body:
      - file: footer/footer.html
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
